### ISSUE TITLE
Question: attachments?

### ISSUE THREAD

**Issue by fisx** [aaronwolen/pandoc-letter#24]
Hi, I would like to attach documents with [something like this](https://pandoc.org/MANUAL.html)

```
![la lune](lalune.jpg "Voyage to the moon")
```

but i'm uncertain how to go about it, or if it is supported at all.  if you help me figure it out i'd be happy to write a PR that adds a hint to the README.

big fan of pandoc-letter, thanks for writing and publishing it!

**Comment by aaronwolen** [comment]
This was an interesting question because I assumed what you propose would work out of the box but it doesn't... 

The reason is pandoc converts markdown images _with_ link text to a floating figure, which the latex letter class does not define. If you remove the link text it works fine, ie

```
![](lalune.jpg "Voyage to the moon")
```

This definitely needs to be added to the docs.

> big fan of pandoc-letter, thanks for writing and publishing it!

You're welcome!

**Comment by aaronwolen** [comment]
Should also note that this syntax works:

```
![](lalune.jpg){ width=50% }
```

**Comment by fisx** [comment]
works, thanks!
